// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0hA0IUHaVoIRhzHkowR-6hB8_SDeRfU',
    appId: '1:976232858282:web:eb52e8819927ccaf9046d3',
    messagingSenderId: '976232858282',
    projectId: 'timestamp-3f055',
    authDomain: 'timestamp-3f055.firebaseapp.com',
    storageBucket: 'timestamp-3f055.appspot.com',
    measurementId: 'G-9EXFVYYWGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUho7GyHgbxjrOGcYewT3SSTHcUYxFRg',
    appId: '1:976232858282:android:3b98a23728fb80979046d3',
    messagingSenderId: '976232858282',
    projectId: 'timestamp-3f055',
    storageBucket: 'timestamp-3f055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoAF3T-zp8UkIRyjmOf5MCK0tSdpaRqjA',
    appId: '1:976232858282:ios:8ea6d18dc0c88ae29046d3',
    messagingSenderId: '976232858282',
    projectId: 'timestamp-3f055',
    storageBucket: 'timestamp-3f055.appspot.com',
    iosBundleId: 'com.example.timestampApp',
  );
}
